openapi: 3.0.0
info:
  title: API Tienda Online "TechStore" (Proyecto 001)
  description: |
    # Documentación Técnica de E-Commerce
    
    Esta API gestiona el catálogo de productos y categorías de la tienda **TechStore**.
    Implementa una arquitectura RESTful estricta con soporte para:
    * Relaciones 1 a Muchos (Categorías -> Productos).
    * Filtrado avanzado de precios.
    * Búsqueda por texto.
    * Paginación de resultados.
  version: 2.1.0-enterprise
  contact:
    name: Equipo de Desarrollo Backend
    email: dev@techstore.example.com

servers:
  - url: https://api.store-example.com/v1
    description: Servidor de Producción
  - url: http://localhost:3000
    description: Entorno Local

paths:
  # ==========================================
  # RECURSO: CATEGORÍAS
  # ==========================================
  /categories:
    get:
      summary: Listar categorías
      tags: [Categories]
      description: Retorna el listado de categorías disponibles.
      responses:
        '200':
          description: Éxito. 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Crear categoría
      tags: [Categories]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Recurso creado correctamente.

  /categories/{id}:
    parameters:
      - $ref: '#/components/parameters/PathId'
    get:
      summary: Obtener categoría por ID
      tags: [Categories]
      responses:
        '200':
          description: Categoría encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Actualizar categoría
      tags: [Categories]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: Actualización exitosa.
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Eliminar categoría
      tags: [Categories]
      responses:
        '200':
          description: Eliminación lógica exitosa.
        '404':
          $ref: '#/components/responses/NotFound'

  # --- RELACIÓN 1 A MUCHOS ---
  /categories/{id}/products:
    get:
      summary: Ver productos de una categoría
      tags: [Categories, Products]
      description: Endpoint relacional que filtra el inventario por la categoría padre.
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: Lista de productos de la categoría.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  # ==========================================
  # RECURSO: PRODUCTOS
  # ==========================================
  /products:
    get:
      summary: Catálogo de productos (Búsqueda Avanzada)
      tags: [Products]
      description: |
        Obtiene productos con opciones de filtrado.
        Permite buscar por nombre, rango de precios y paginar resultados.
      parameters:
        - name: search
          in: query
          description: Buscar por nombre del producto (ej. "Laptop").
          schema:
            type: string
        - name: min_price
          in: query
          description: Precio mínimo.
          schema:
            type: number
        - name: max_price
          in: query
          description: Precio máximo.
          schema:
            type: number
        - name: limit
          in: query
          description: Cantidad de resultados (Paginación).
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Resultados de la búsqueda.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Registrar nuevo producto
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Producto registrado en inventario.
        '400':
          $ref: '#/components/responses/BadRequest'

  /products/{id}:
    parameters:
      - $ref: '#/components/parameters/PathId'
    get:
      summary: Detalle de producto
      tags: [Products]
      responses:
        '200':
          description: Datos del producto.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Modificar producto
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Producto modificado.
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Dar de baja producto
      tags: [Products]
      responses:
        '200':
          description: Producto eliminado del inventario.
        '404':
          $ref: '#/components/responses/NotFound'

# ==========================================
# COMPONENTES REUTILIZABLES
# ==========================================
components:
  parameters:
    PathId:
      name: id
      in: path
      required: true
      description: Identificador único del recurso.
      schema:
        type: integer

  responses:
    NotFound:
      description: 404 Not Found - El recurso no existe en la base de datos.
    BadRequest:
      description: 400 Bad Request - Faltan campos obligatorios o formato inválido.

  schemas:
    # --- CATEGORÍA ---
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Electrónica"
        description:
          type: string
          example: "Dispositivos y gadgets"
    
    CategoryInput:
      type: object
      required: [name]
      properties:
        name:
          type: string
          example: "Hogar"
        description:
          type: string
          example: "Artículos para la casa"

    # --- PRODUCTO ---
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 101
        name:
          type: string
          example: "Smart TV 55 Pulgadas"
        price:
          type: number
          example: 450.50
        stock:
          type: integer
          description: Unidades disponibles
          example: 25
        categoryId:
          type: integer
          description: ID de la categoría padre
          example: 1
    
    ProductInput:
      type: object
      required: [name, price, categoryId]
      properties:
        name:
          type: string
          example: "Licuadora Pro"
        price:
          type: number
          example: 80.00
        stock:
          type: integer
          example: 10
        categoryId:
          type: integer
          example: 2